name: PR message info

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commits_url = context.payload.pull_request.commits_url
            const results = await github.request(commits_url)
            console.log(results.data[0].commit.message)
            
            const options = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.payload.number
            }
            console.log(github.issues.createComment)
            await github.issues.createComment(options)
